<?xml version="1.0"?>
<robot>
 
  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
      iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
      izz="${m*r*r/2}"/>
  </macro>

  <macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
      iyy="${m*(x*x+z*z)/12}" iyz = "0"
      izz="${m*(x*x+z*z)/12}"/>
  </macro>

  <macro name="sphere_inertia" params="m r">
    <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
      iyy="${2*m*r*r/5}" iyz = "0"
      izz="${2*m*r*r/5}"/>
  </macro> 

  <macro name="wheel" params="lr tY">

    <link name="${lr}_wheel">
       <collision>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <geometry>
            <cylinder length="${wheel_Width}" radius="${wheel_Radius}"/>
          </geometry>
       </collision>

       <visual>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <geometry>
            <cylinder length="${wheel_Width}" radius="${wheel_Radius}"/>
          </geometry>
          <material name="black"/>
       </visual>

       <inertial>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <mass value="${wheel_Mass}"/>
           <cylinder_inertia m="${wheel_Mass}" r="${wheel_Radius}" h="${wheel_Width}"/>
       </inertial>
    </link>

    <gazebo reference="${lr}_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Black</material>
    </gazebo>


    <joint name="${lr}_wheel_hinge" type="continuous">
      <parent link="chassis"/>
      <child link="${lr}_wheel"/>
      <origin xyz="${+wheel_Pos-chassis_Length/4} ${tY*wheel_Width/2+tY*chassis_Width/2} ${wheel_Radius}" rpy="0 0 0" /> 
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

  </macro>


</robot>
