<?xml version="1.0"?>
<robot name="myrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">
        <!-- Put here the robot description -->

   <xacro:property name="PI" value="3.1415926535897931"/>
   <xacro:property name="mass" value="75" /> <!-- 75 kg -->

   <xacro:property name="chassis_Height" value="0.1"/>
   <xacro:property name="chassis_Length" value="0.55"/>
   <xacro:property name="chassis_Width" value="0.5"/>
   <xacro:property name="chassis_Mass" value="50"/>
   
   
   <xacro:property name="wheel_Width" value="0.04" />
   <xacro:property name="wheel_Length" value="0.2" />
   <xacro:property name="wheel_Mass" value="5" />
   <xacro:property name="wheel_Pos" value="0.2" />
   <xacro:property name="wheel_Radius" value="0.1"/>

   <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->

   <xacro:include filename="$(find myrobot_description)/urdf/myrobot.gazebo" />
   <xacro:include filename="$(find myrobot_description)/urdf/materials.xacro" />
   <xacro:include filename="$(find myrobot_description)/urdf/macros.xacro" />

     <!-- Base link --> 
    <link name="base_link" />

  <link name="chassis">
    <collision>
      <origin xyz="0 0 ${chassis_Height*3}" rpy="0 0 0"/>
      <geometry>
	<box size="${chassis_Length} ${chassis_Width} ${chassis_Height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${chassis_Height*3}" rpy="0 0 0"/>
      <geometry>
	<box size="${chassis_Length} ${chassis_Width} ${chassis_Height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${chassis_Height*3}" rpy="0 0 0"/>
      <mass value="${chassis_Mass}"/>
      <inertia ixx="${chassis_Mass / 12.0 * (chassis_Width*chassis_Width + chassis_Height*chassis_Height)}" ixy="0.0" ixz="0.0"
               iyy="${chassis_Mass / 12.0 * (chassis_Height*chassis_Height + chassis_Width*chassis_Width)}" iyz="0.0"
               izz="${chassis_Mass / 12.0 * (chassis_Width*chassis_Width + chassis_Width*chassis_Width)}"/>
    </inertial>
  </link>

  <joint name="base_link_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint>


  <joint type="continuous" name="right_back_wheel_joint">
      <parent link="chassis"/>
      <child link="right_back_wheel"/>
      <origin xyz="${-chassis_Width/2 + wheel_Length + wheel_Radius*2} ${-chassis_Width/2 - wheel_Width/2} ${wheel_Radius}" rpy="0  ${PI/2} ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/>
   </joint>


   <link name="right_back_wheel">
      <origin xyz="0 0 0" rpy="0 0 0"/>

      <collision name="collision">
        <geometry>
	  <cylinder radius="${wheel_Radius}" length="${wheel_Width}" />
        </geometry>
      </collision>

      <visual name="visual">
	<geometry>
	  <cylinder radius="${wheel_Radius*1.65}" length="${wheel_Width}"/>
	</geometry>
	<material name="orange"/>
      </visual>

      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
   </link>




   <joint type="continuous" name="left_back_wheel_joint">
      <parent link="chassis"/>
      <child link="left_back_wheel"/>
      <origin xyz="${-chassis_Width/2 + wheel_Length + wheel_Radius*2} ${chassis_Width/2 + wheel_Width/2} ${wheel_Radius}" rpy="0   ${PI/2} ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/>
   </joint>


   <link name="left_back_wheel">
      <origin xyz="0 0 0" rpy="0 0 0"/>

      <collision name="collision">
        <geometry>
	  <cylinder radius="${wheel_Radius}" length="${wheel_Width}" />
        </geometry>
      </collision>

      <visual name="visual">
	<geometry>
	  <cylinder radius="${wheel_Radius*1.65}" length="${wheel_Width}"/>
	</geometry>
	<material name="orange"/>
      </visual>

      <inertial>
        <mass value="0.1" />
        <origin xyz="10 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
   </link>


   <joint type="continuous" name="right_front_wheel_joint">
      <parent link="chassis"/>
      <child link="right_front_wheel"/>
      <origin xyz="${-chassis_Width/2 + wheel_Length/4 + wheel_Radius/2} ${-chassis_Width/2 - wheel_Width/2} ${wheel_Radius}" rpy="0 ${PI/2} ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/>
   </joint>


   <link name="right_front_wheel">
      <origin xyz="0 0 0" rpy="0 0 0"/>

      <collision name="collision">
        <geometry>
          <sphere radius="${wheel_Radius}"/>
	</geometry>
      </collision>

      <visual name="visual">
	<geometry>
          <sphere radius="${wheel_Radius}"/>
	</geometry>
	<material name="orange"/>
      </visual>

      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
   </link>


   <joint type="continuous" name="left_front_wheel_joint">
      <parent link="chassis"/>
      <child link="left_front_wheel"/>
      <origin xyz="${-chassis_Width/2 + wheel_Length/4 + wheel_Radius/2} ${chassis_Width/2 + wheel_Width/2} ${wheel_Radius}" rpy="0 ${PI/2} ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/>
   </joint>


   <link name="left_front_wheel">
      <origin xyz="0 0 0" rpy="0 0 0"/>

      <collision name="collision">
        <geometry>
          <sphere radius="${wheel_Radius}"/>
        </geometry>
      </collision>

      <visual name="visual">
	<geometry>
          <sphere radius="${wheel_Radius}"/>
	</geometry>
	<material name="orange"/>
      </visual>

      <inertial>
        <mass value="0.1"/>
        <origin xyz="10 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
   </link> 



   <!-- Hokuyo Laser -->
   <joint name="hokuyo_joint" type="fixed">
     <axis xyz="0 1 0" />
     <origin xyz="${chassis_Length/2-0.03} 0 ${chassis_Height+0.03}" rpy="0 0 0"/>
     <parent link="chassis"/>
     <child link="hokuyo_link"/>
   </joint>

   <link name="hokuyo_link">
     <collision>
       <origin xyz="0 0 0" rpy="0 0 0"/>
       <geometry>
	 <box size="0.1 0.1 0.1"/>
       </geometry>
     </collision>

     <visual>
       <origin xyz="0 0 0.33" rpy="0 0 0"/>
       <geometry>
        <mesh filename="package://myrobot_description/meshes/hokuyo.dae"/>
       </geometry>
     </visual>

     <inertial>
       <mass value="1e-5" />
       <origin xyz="0 0 0" rpy="0 0 0"/>
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
     </inertial>
   </link>


	<!-- Camera -->
   <joint name="camera_joint" type="fixed">
     <axis xyz="0 1 0" />
     <origin xyz="${camera_link/2 + chassis_Length/2} 0 ${chassis_Height/2}" rpy="0 0 0"/>
     <parent link="chassis"/>
     <child link="camera_link"/>
   </joint>

   <link name="camera_link">
     <collision>
       <origin xyz="0 0 0" rpy="0 0 0"/>
       <geometry>
	 <box size="${camera_link} ${camera_link} ${camera_link}"/>
       </geometry>
     </collision>

     <visual>
       <origin xyz="-0.05 0 0.35" rpy="0 0 0"/>
       <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
       </geometry>
       <material name="red"/>
     </visual>

     <inertial>
       <mass value="1e-5" />
       <origin xyz="0 0 0" rpy="0 0 0"/>
       <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
     </inertial>
   </link>

  <!--generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames 
       so that ros and opencv can operate on the camera frame correctly -->

   <joint name="camera_optical_joint" type="fixed">
     <!-- these values have to be these values otherwise the gazebo camera image
         won't be aligned properly with the frame it is supposedly originating from -->
     <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
     <parent link="camera_link"/>
     <child link="camera_link_optical"/>
   </joint>

   <link name="camera_link_optical">
   </link>

   <transmission name="tran1">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="left_back_wheel_joint">
       <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="motor1">
       <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
   </transmission>

   <transmission name="tran2">
     <type>transmission_interface/SimpleTransmission</type>
     <joint name="right_back_wheel_joint">
       <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
     </joint>
     <actuator name="motor2">
       <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
       <mechanicalReduction>1</mechanicalReduction>
     </actuator>
   </transmission>

</robot>
